### ISSUE TITLE
Error When compiling with Vite

### ISSUE THREAD

**Issue by SimonLou-Dev** [teodosii/react-notifications-component#107]
Hello, I  have install this components, he work when i make 'yarn dev' but i have this error when i make 'yarn build'

![2021-04-07 16_48_41-Outils de développement - BCFD - Intranet - http___127 0 0 1_8000_](https://user-images.githubusercontent.com/36455117/113887003-668e0d80-97c1-11eb-8929-cd3a9e630b32.png)

my vite.config.js

`<pre>
import { defineConfig } from 'vite'
import reactRefresh from '@vitejs/plugin-react-refresh'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [reactRefresh()],
    root: './resources',
    base: '/assets/',
    mode: "development",
    build: {
      outDir: '../public/assets',
        assetsDir: '',
        manifest: true,
        minify: false,
        rollupOptions: {
          output: {
              manualChunks: undefined
          },
          input:{
              'app.jsx': './resources/js/app.jsx'
          }
        }
    }
})
</pre>
`

I searched for a long time but I still have not found, Thank You

**Comment by knipl** [comment]
I have the same issue, also while using with Vite.js

**Comment by teodosii** [comment]
Unfortunately I don't work with Vite, anyone willing to give some help is encouraged! Feel free to drop a PR or a comment here, at the time being I don't have a clue for this.

**Comment by lkuich** [comment]
@teodosii My above work around worked for us. I think I have a lead on the cause, I'll see if I can get a PR together on Monday 👍
