### ISSUE TITLE
TypeError: this.add is not a function

### ISSUE THREAD

**Issue by ALi-Hosseinzad** [teodosii/react-notifications-component#119]
followed the steps on the NPM page for react-notifications-component but I keep getting "TypeError: this.add is not a function".

Steps:

    Install using npm install react-notifications-component.
    Install animate.css using npm install animate.css.
    Import react-notifications-component and store.

However, I just keep getting a **TypeError: this.add is not a function**

```
import "animate.css/animate.min.css";
import "react-notifications-component/dist/theme.css";
import { store } from "react-notifications-component";

export const notification = (title = "", type, message = "") => {
  return store.addNotification({
    title: title,
    type: type,
    message: message,
    insert: "top",
    container: "top-left",
    animationIn: ["animate__animated", "animate__fadeIn"],
    animationOut: ["animate__animated", "animate__fadeOut"],
    dismiss: {
      duration: 3000,
      onScreen: true,
    },
  });
};
```

**Comment by DennieMello** [comment]
i have the same problem

**Comment by Jonas-Args** [comment]
Have you guys added this  `<ReactNotification />` in your application?

**Comment by PlaceblockHD** [comment]
Same Problem Here (I have added `<ReactNotification />`)

**Comment by ALi-Hosseinzad** [comment]
> Have you guys added this `<ReactNotification />` in your application?

yes, I added and it was resolved, thank you
