### ISSUE TITLE
Exported types have bad imports and there's no "types" record in package.json

### ISSUE THREAD

**Issue by pbitkowski** [teodosii/react-notifications-component#124]
Hi,

Your package looks great, kudos for building it! I would love to use it but when I import it I get TypeScript error:
```
TS2307: Cannot find module 'react-notifications-component' or its corresponding type declarations.
```
I checked your index.d.ts and see: 
```typescript
import container from 'src/components/Container';
import store from 'src/store';
export { store };
export default container;
```
Where there's no src directory

Also in package.json there's no "types" record that would indicate where to search types. 

Repro: 
https://codesandbox.io/s/relaxed-saha-4sxqn?file=/src/App.tsx

I could help you with exporting types if you want :)

**Comment by teodosii** [comment]
Feel free to add the changes in a PR, it will be much appreciated. Thanks!

**Comment by OkancanCosar** [comment]
is it about installing types? 
yarn add @types/react-notifications-component

**Comment by teodosii** [comment]
The declarations are in the build folder, but for some reason the `index.d.ts` had the imports referenced from `src` instead of `.` Watch out for the next release, will have this fixed.

@pbitkowski
