### ISSUE TITLE
My app using 3.1.1 fails after npm install because package.json says it is 3.3.2

### ISSUE THREAD

**Issue by craigmcc** [teodosii/react-notifications-component#134]
I have an existing application (based on React 17) that uses react-notifications-component 3.1.1.  However, if you need to reinstall the dependencies, the package.json in react-notifications-component says it is version 3.2.2 -- which (of course) triggers compile errors because of the:
* Removal of default imports.
* Change of "store" to "Store".
* Change of "ReactNotification" to "ReactNotifications" (which isn't updated in the docs, by the way).

Is it possible that, when the npm publish occurred, it overwrote the 3.1.1 version with 3.3.2 due to a not-updated version number somewhere?

**Comment by teodosii** [comment]
`3.3.2` is latest and stable. `3.2.X` had some issues and needed several releases to figure out the problem. As for `3.1.1` that was never released, it's either `3.1.0` or `3.2.X`, and latest  is `3.3.2`

![image](https://user-images.githubusercontent.com/40542072/151543105-0c5710ce-87bc-485f-b89c-69e0f52c8f25.png)

^ docs on github readme had been updated once `3.3.2` was out

**Comment by teodosii** [comment]
Release table here on NPM

![image](https://user-images.githubusercontent.com/40542072/151544119-cdf7a471-94af-4a9f-b967-c6d999ec5592.png)
