### ISSUE TITLE
Eror: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by fahrettinrizaergin** [teodosii/react-notifications-component#137]
When I upgrade from version 3.1.0 to version 3.2.2, I get an error like in the picture can you help?
![indir (1)](https://user-images.githubusercontent.com/87656030/151604585-a59d7571-3f41-49c5-b5b0-688f3da52ecd.png)

**Comment by itsmichaeldiego** [comment]
I am having the same issue @fahrettinrizaergin

**Comment by itsmichaeldiego** [comment]
I am having the same issue @fahrettinrizaergin 

In order to fix it for me, I had to fix the version to be `3.1.0` :

```json
"react-notifications-component": "3.1.0",
```

**Comment by fahrettinrizaergin** [comment]
I fixed the problem using version 3.1 again, thank you.

**Comment by teodosii** [comment]
I will let the other issue as open and close this one. Try `3.3.11`, it should be parsed by babel and result in browser complying code.
