### ISSUE TITLE
Does store.removeNotification(id) not remove notification from dom?

### ISSUE THREAD

**Issue by AndreaEsposit** [teodosii/react-notifications-component#140]
I have noticed that ` store.removeNotification(id)` does not remove notifications from the DOM, is there something wrong with my setup?

```
export const warning= (message) => {
    Store.addNotification({
        content: ({ id }) => <NotifyCard id={id} title="Something went wrong updating the data" details={message} type="Warning" />,
        insert: 'bottom',
        container: 'bottom-center',
        animationIn: ['animate__animated', 'animate__fadeIn'],
        animationOut: ['animate__animated', 'animate__fadeOut'],
        dismiss: {
            duration: 0,
            showIcon: true,
            click: false,
        },
        width: convertRemToPixels(37),
    });
};
```

Inside <NotifyCard/> I have a button with onClick={() => Store.removeNotification(id)}, the notification does disappear on click, but it remains in the DOM

I can also see that onRemoval is not being triggered by Store.removeNotification

I am using version 3.3.11 (the one on npm)

**Comment by teodosii** [comment]
There was a fix for something else which broke this, should be fine now. It also affected github pages, thanks for reporting! 

Reopen if any other issue!
