### ISSUE TITLE
How to give width to notification in percentage

### ISSUE THREAD

**Issue by jsUser1** [teodosii/react-notifications-component#141]
### How to give width to notification in percentage
How can I apply width in percentage to the notifications, which is supposed to be shown at top of the screen, something like shown in the attached picture.
![This is Image](https://user-images.githubusercontent.com/53461997/153152963-c3722b4b-a3eb-4b15-a0f0-f6cda21872be.png)

In the previous version, there was a .notification class, through which I was able to give inline CSS for width in percentage like this:
.rnc__notification-container--top-center .notification {
     width: 100% !important;
 }
But now this class has been removed. I don't want to give width in px.

**Comment by jsUser1** [comment]
Right now it is displaying like this:
![Screenshot (154)](https://user-images.githubusercontent.com/53461997/153154581-34229677-8dca-4772-93e4-a4fd2951f951.png)

**Comment by teodosii** [comment]
I've added it back in `3.4.1`, use `rnc__notification`.

**Comment by jsUser1** [comment]
Thank you so  much.... :-)
