### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'addNotification')

### ISSUE THREAD

**Issue by staminna** [teodosii/react-notifications-component#144]
package.json file:
```
"react": "^17.0.1",
"react-dom": "^17.0.1",
"react-notifications-component": "^3.4.1"
```

notification-handler.js

```
import { store } from 'react-notifications-component';
import 'react-notifications-component/dist/theme.css';

const renderNotification = (type, title, message) => {
  store.addNotification({
    title: `${title}!`,
    message,
    type,
    insert: "top",
    container: "top-center",
    animationIn: ["animate__animated", "animate__fadeIn"],
    animationOut: ["animate__animated", "animate__fadeOut"],
    dismiss: {
      duration: 5500,
      onScreen: true
    }
  });
};

export default renderNotification;
```

App.js
import { ReactNotifications } from 'react-notifications-component';
import renderNotification from '../utils/notification-handler';

  render() {
    return (
      <Router>

        <div >
          <ReactNotifications />
...

Then  renderNotification('success', 'Success', `Festival Created Successfully!`);

Error:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addNotification')
    at renderNotification (notification-handler.js:5:1)

**Comment by teodosii** [comment]
Uppercase `Store`

```jsx
import { Store } from 'react-notifications-component'
```

**Comment by staminna** [comment]
Thanks!
