### ISSUE TITLE
Scrolling when screen is full of notifications

### ISSUE THREAD

**Issue by Trev-Robertson** [teodosii/react-notifications-component#146]
Once you get enough notifications they start to populate off screen. is it possible to scroll vertically to see these notifications?

**Comment by teodosii** [comment]
It can be done by the consuming client easily if css is changed I believe. You can set the containers' `max-height` to `100vh` I believe, add `overflow-y: auto` and use your custom slider (the browser's slider would be pretty ugly).

**Comment by Trev-Robertson** [comment]
Thanks! I foolishly forgot to add a max height.
