### ISSUE TITLE
Fade In animation suddenly appears instead of playing the animation 

### ISSUE THREAD

**Issue by Loque18** [teodosii/react-notifications-component#154]
I noticed that when you dispatch a notification using the fade in animaton it doesn't play the animation, instead it just suddenly appears, but this happens only when you dispatch the first notification, the animation plays for the others notifications, but not for the first one. 

stepts to reproduce 
[Open the demo app](https://teodosii.github.io/react-notifications-component/ ) and go to the animation entrance section and dispatch a fade in animation 
![image](https://user-images.githubusercontent.com/28642447/167003523-91afaeb6-6ad2-4711-947e-b27be0632d05.png)

**Comment by teodosii** [comment]
Thanks for reporting. It seems just the fadeIn and flipInX aren't working. Probably just a CSS thing. Not gonna investigate it anytime soon since all others work so I'm assuming it's missing a class or the name was changed.

**Comment by teodosii** [comment]
Fixed now! It had wrong `animated__` class

**Comment by Loque18** [comment]
> Fixed now! It had wrong `animated__` class

Thank you so much!!
