### ISSUE TITLE
npm ERR! Missing script: "build:library:dev"

### ISSUE THREAD

**Issue by monim-es** [teodosii/react-notifications-component#160]
I installed **react-notifications-component** with  `npm install react-notifications-component`  . then I tried to build the library as it is mentioned in the docs   :  `npm run build:library:dev`  but it  giving me this error  : 

**### npm ERR! Missing script: "build:library:dev"**
 please what  am I doing wrong ?

**Comment by teodosii** [comment]
If you installed it through NPM then import the library into your codebase, follow the examples and you're good to go.

If on the other hand you want to have the library built, you use `npm run build:library:dev` but that's if you cloned/fetched the repo and you want to build/change it locally. (this is for `Development` only, not for `usage`)

I believe you only want to use it in your application, therefore use the first option.

![image](https://user-images.githubusercontent.com/40542072/185384738-6be1c249-73de-4458-98c6-6dd2d1611b3d.png)

**Comment by monim-es** [comment]
thanks for your help  !

**Comment by teodosii** [comment]
No problem. If you face any other issue feel free to open a new issue, don't reply into closed ones.
