### ISSUE TITLE
'message' property renders only string, not component

### ISSUE THREAD

**Issue by ghost** [teodosii/react-notifications-component#169]
The documentation and type definitions say that 'message' property could be a string or component
`NotificationTitleMessage = string | React.ReactNode | React.FunctionComponent;`

In reality, passing a component to this property renders nothing

Example:
https://codesandbox.io/s/react-notifications-component-message-1sgkd8

**Comment by teodosii** [comment]
Oh, it's a mistake on the typings. `Message` doesn't accept a component but a `JSX.Element` - you can see it [here](https://github.com/teodosii/react-notifications-component/blob/master/src/components/Notification.tsx#L324) in the code

If you change your example into

```jsx
import "./styles.css";
import { ReactNotifications, Store } from 'react-notifications-component'
import 'react-notifications-component/dist/theme.css'

export default function App() {
  function a() {
    Store.addNotification({
      title: "Wonderful!",
      message: <div>123</div>,
      type: "success",
      container: "top-right",
      dismiss: { duration: 0}
    });
  }

  return (
    <div className="App">
      <ReactNotifications />
      <h1 onClick={a} >Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}
```

you'll see it works with JSX instead.
