### ISSUE TITLE
dist/react-notifications-component.js is missing from the latest build, not able to install it via npm install

### ISSUE THREAD

**Issue by circleapps** [teodosii/react-notifications-component#19]
dist/react-notifications-component.js is missing from the latest build, not able to install it via npm install.

**Comment by GiovanniIncammicia** [comment]
Same here, when I build I get a
`Module` not found: Can't resolve 'react-notifications-component' in 'C:\...\project\src'
I tried to revert the version number but still got the same error.

**Comment by MohamedLamineAllal** [comment]
Same here
![Screenshot from 2019-03-28 14-58-31](https://user-images.githubusercontent.com/20062543/55163875-e0b74080-516a-11e9-8093-8c22f8b5777d.png)

**Comment by MohamedLamineAllal** [comment]
As a temporal workaround till it get fixed. Here a cloned repo, where i run the build. 
You find it here
https://github.com/MohamedLamineAllal/react-notifications-component/tree/master/dist
copy all the content of dist, and past it in your node_module/react-noti.../dist. It will work. When the update happen, uninstall and reinstall. (hope this help)

**Comment by easmith** [comment]
"react-notifications-component": "1.0.1",
work for me

**Comment by teodosii** [comment]
Looking at it now, will fix it in a moment

**Comment by teodosii** [comment]
I've added another build on NPM `1.1.1` and this one is working on my machine. Have no clue why the other didn't work.
