### ISSUE TITLE
Change Notification Color

### ISSUE THREAD

**Issue by atifaziz2** [teodosii/react-notifications-component#20]
Hi!
I need to be change notification color according to my app theme color. I didn't see any props or style in documentation to change color.

Thanks

**Comment by teodosii** [comment]
Use custom content, you'll be able to define as many notification types as you want. Option is documented in the `README` and there are few examples on GitHub pages.

**Comment by ding-ma** [comment]
Hi,

I currently using the library and I love it! However, I'm struggling with the documentation. Could you provide me an example to how we can change the notification color? This is the snippet of code that I am using.

```
handleNotificationSuccess = () => {
        store.addNotification({
            title: 'Email Sent!',
            message: 'I will contact you as soon as possible!',
            type: 'success',
            container: 'top-right',
            insert: 'bottom',
            animationIn: ['animated', 'fadeIn'],
            animationOut: ['animated', 'fadeout'],
            dismiss: {
                duration: 7000,
                showIcon: true,
                pauseOnHover: true
            },
            width: 300
        })
    };
```

**Comment by finnbear** [comment]
It is certainly possible to create custom notification types but it looks like the color for a given type is defined in the theme css. I would prefer an easier way to define the color of each custom type such as a map of type to color(s).

**Comment by btesanovic** [comment]
I have override default theme styles importing custom css just after default one

```
import { Store } from 'react-notifications-component';
import 'react-notifications-component/dist/theme.css';
import 'animate.css/animate.min.css';
import './notify.css'
```

**notify.css** only 3 variants i used default success warning , class  rnc__notification-message is for text color

```
.rnc__notification-item--default {
    background-color: #72adec;
    border-left: 8px solid #0562c7;
}
.rnc__notification-item--success {
    background-color: #a0f6c2;    
}
.rnc__notification-item--warning {
    background-color: #f6d9a0;    
}
.rnc__notification-message{
    color: #444;
}
```
