### ISSUE TITLE
No animation?

### ISSUE THREAD

**Issue by bobdeei** [teodosii/react-notifications-component#21]
Hello,

I have imported the `.css` for styling, but no animation yet. The `.css` file does not have style for animation.

I notice there is a `.js.map` file, which might relate to the command line `npm run build:library:dev`. Running this command causes error.

How can I build this file?

---

One more thing, in https://teodosii.github.io/react-notifications-component/, the example does not import the `.css` file like the doc on this Github page. This should be note on top that the `.css` needs to be imported for new developers get it working quickly.

**Comment by teodosii** [comment]
On GitHub pages I've forgotten to add the css import, my bad. The css files only contain styles for the notifications, they do not have any animation classes for now - that's a plan for version `2.0.0` to have some animations available by default when you import the library.

For animations I'd recommend a library like `animate.css`, that's the library used in the samples.

**Comment by bobdeei** [comment]
Really nice @teodosii! I have include the `anime.css` and it works like charm!

There's another React Notification package but I chose this one because I like the design. I think you should clearly mention the need to import `.css` that goes with the package and the extra `animate.css` for animation in the doc. This should help other developers get things up quickly.

Thank you very much for the answer. Keep up the good work!

**Comment by teodosii** [comment]
Ok, will do that. Thank you for choosing my library :satisfied:

**Comment by kesarion** [comment]
This should really be documented somewhere. Or at the very least there should be an open issue for it, noting the workaround with `animate.css`.

**Comment by chitgoks** [comment]
agreed. and how to get animate.css

**Comment by Gibolt** [comment]
Note to anyone who needs it, you now have to use the Compat version.

`import 'animate.css/animate.compat.css'`

**Comment by DXAizpiri** [comment]
First of all thank you so much because taking the time of doing so awesome notification package @teodosii !! I've been strugling for few minutes why even I followed your steps (including the animate.css import) the notifications weren't animated, then I noticed that the documentation was outdated in the part which indicates as example this:

      animationIn: ["animate__animated", "animate__fadeIn"],
      animationOut: ["animate__animated", "animate__fadeOut"],

The current way would be like this, without the double underscore:

      animationIn: ["animated", "fadeIn"],
      animationOut: ["animated", "fadeOut"],

I hope this could help to anyone who could face the same issue. Bye and thanks again!
