### ISSUE TITLE
Refer the <ReactNotifications /> from children component?

### ISSUE THREAD

**Issue by bobdeei** [teodosii/react-notifications-component#22]
Hi, I have new issue. I already have solution, but want a more concise one.

How can I fire the event in nested components directly without passing through many component layers?

So because of the position issue, the `<ReactNotifications />` is placed at the top level in the component tree, or in `<App />`. I did the same.

However, I have some children components, or actually grand children components which need to fire the alert event of `<ReactNotifications />` in `<App />`.

The current solution is to pass the event handler to the grand children. If the component tree gets complicated, what else can we do in order to achieve the same result with less code?

Here's the example code from [CodeSanbox.io](https://codesandbox.io/s/2vmxz02pjp). 

```
class App extends Component {
  displayNotification = () => {
    console.log(this.ref);
    this.ref.addNotification({
      title: "Awesomeness",
      message: "Awesome Notifications!",
      type: "success",
      insert: "top",
      container: "top-right",
      animationIn: ["animated", "fadeIn"],
      animationOut: ["animated", "fadeOut"],
      dismiss: { duration: 2000 },
      dismissable: { click: true }
    });
  };
  render() {
    return (
      <div>
        <h1>App Component</h1>
        <ReactNotifications ref={ref => (this.ref = ref)} />
        <Parent notify={this.displayNotification} />
      </div>
    );
  }
}

const Parent = ({ notify }) => (
  <div>
    <h2>Parent</h2>
    <Child notify={notify} />
  </div>
);

const Child = ({ notify }) => (
  <div>
    <h3>Child</h3>
    <GrandChild notify={notify} />
  </div>
);

const GrandChild = ({ notify }) => (
  <div>
    <h4>GrandChild</h4>
    <button onClick={notify}>Click for notification</button>
  </div>
);
```

In this example, how can I invoke the alert event from GrandChild without passing the event handler through App > Parent > Child > GrandChild?

Without referring to the ultimate `<ReactNotifications />` on top component`<ReactNotifications />`, all the alerts will overlap on one another if many `<ReactNotifications />` is used.

What is the solution? Redux can solve the state issue, but this is event handler?

Thank you
Duy

**Comment by teodosii** [comment]
Use context API, it lets you pass props deep without manually doing it for each of the component in the tree. Isn't that what you asked for?

**Comment by bobdeei** [comment]
I forgot to mention. I'm using Redux in this project.

At first, I think the library provide some abstraction for that purpose. But Context API can solve this like you said.

So Can I use Context with Reduz at the same time?

**Comment by teodosii** [comment]
To be honest I haven't played much with both of these, but why cannot you use context API together with Redux? With Redux your component is tied to the store so any time the store it's updated you get the reflected changes in the props, while with context you just read some data from grandgrand...parent. I doubt Redux has helpers to simplify usage of context API, and I don't think there's any restriction to mix both. 

Might be useful to show some context/redux examples in the docs but at the moment I'm caught with some other project that I wish to publish soon.

**Comment by teodosii** [comment]
Just a quick question for you, how are you currently using Redux with this component? You have a HOC that renders `react-notifications` and a ref to it, I guess. How do you call `addNotification` on that ref by mutating the state, if you are using it with a HOC? Or are you using it otherwise? If so, how?

**Comment by bobdeei** [comment]
The way I do it is as same as the code example from CodeSandbox I provided. Using Redux or not, it is the same. I still need to render `react-notifications` at the top level component `<App />` to solve the position issue, and pass down the event handler that display message from `<App />` to children components. At these children components, along with calling `dispatch` for update state, the event handler for displaying message is also called. So whether I implement Redux or not, I still have to pass these event handlers down the component tree. This, I found, has nothing to do with Redux.

Here's the [live code](https://codesandbox.io/s/jpq0yrq413) from CodeSandbox for simple Todo app that utilize Redux and your `react-notifications`.

I have no idea how to call `addNotification` from children components rather than passing the event handlers down the tree.

I hope my code is not too messy and difficult to read.

**Comment by teodosii** [comment]
I know it's a stupid question but did you have a look at docs on context? In my opinion it clearly explains how to consume the context, and it's the only way to skip passing down prop for each nested component. If you had, is there something not clear in the docs or am I missing any technical aspect?

I will mark this as a todo to update docs showing an example for context usage, but can't say when as I'm a bit short on time.

**Comment by bobdeei** [comment]
I mean I can use merely Context for this. But I'm using Redux right now. Though Redux implements Context under the hood but I really don't know how to make use of Context when writing with Redux.

My point is I rewrite my app with Context to solve that problem. But I lose the joy Redux gives me. I want to keep Redux and take advantage of Context for that. I have not seen anybody apply two of these at the same time.

I'll try to figure it out later. If there's a solution, I'll let you know.

**Comment by bobdeei** [comment]
Hi @teodosii ,

I just implement Redux with Context and it works successfully without any conflict. So for future documentation, anyone who chooses to combine Redux for state management can use Context for passing notification method around. It's the way to solve the problem I presented.
