### ISSUE TITLE
Encountered two children with the same key

### ISSUE THREAD

**Issue by Rhuansantos** [teodosii/react-notifications-component#23]
I am getting a react unique key error. I do have two questions about that. 
Could we use some library like UUID to generate unique keys, instead of using the item.id?
Another thing that I also notice is that even after the element is not showing on the screen anymore it still on the dom. 
I would be more than happy to send a PR.

https://github.com/teodosii/react-notifications-component/blob/master/src/react-notification-component.js#L204

![Screen Shot 2019-05-05 at 3 34 47 AM](https://user-images.githubusercontent.com/2942805/57190327-e41ab600-6ee6-11e9-8bd4-79fd053d9252.png)

**Comment by teodosii** [comment]
Hey,
`addNotification` supports using your own ID so that 2 keys will never conflict. If you're not supplying an ID then Math.random will be used instead

**Comment by teodosii** [comment]
For the other thing, could you show an example? If it is related to the conflicting keys, then it makes sense, React component gets corrupted and it's not rendering properly.

**Comment by Rhuansantos** [comment]
I can definitely try to put that in a small code sample, but for the time being, look at how my app is rendering the notifications now. I gave it a unique id at the parent level however I am not sure how I could do the same in the children level, I haven't deep look at the code but at least I don't see anything in the docs.
I believe only removing the element out of the dom after is not on the screen anymore should solve the problem. If we have a case where you can have multiple children then each of them should have a unique id right?

![Screen Shot 2019-05-05 at 5 29 31 PM](https://user-images.githubusercontent.com/2942805/57200541-6644c200-6f5b-11e9-9990-0ca2fc4e2634.png)

**Comment by teodosii** [comment]
The key at the root level has nothing to do with the keys at notification level. I suppose something gets corrupted somewhere but I don't know how to reproduce it. Is the console showing any other warnings or errors before this key error? Also a sample code would help.

And, as I've said in the previous post, if you want custom ID/keys over the notifications, supply that ID to the `addNotification` call.
