### ISSUE TITLE
Does this package only works on onclick event?

### ISSUE THREAD

**Issue by yashshukla1912** [teodosii/react-notifications-component#24]
Hi
I want to show notification on creating a new ticket, but i am getting an error `"Cannot read property 'addNotification' of null"`. i am sharing a snippet of my code, will you please help me to find where i am going wrong.
`render() {
      if(this.props.newTicket.createdTicket){
			this.addNotification()
		}
}`
i have tried this on onClick event, it worked fine but here i want to display notification if my state createdTicket is true on page render.
![ss](https://user-images.githubusercontent.com/51371310/61539722-b959eb80-aa59-11e9-8b50-e6aa01357fce.png)

**Comment by teodosii** [comment]
Do not call it inside render, move the call to componentDidUpdate/componentDidMount

**Comment by yashshukla1912** [comment]
i tried this as well it didnt helped, it shows same error
`TypeError: Cannot read property 'addNotification' of null`
![error](https://user-images.githubusercontent.com/51371310/61609574-2a74eb00-ac74-11e9-9247-b935dc280e39.png)

**Comment by teodosii** [comment]
This isn't package related, as I can see in your last post it crashes due to null reference of `this.notificationDOMRef.current`. Your ref isn't set up or not working properly, can't really tell from the last example.

Package is not tied to `onClick` event, samples show usage with `onClick` but it's not limited to that. As long as you have a reference to the component you are able to call `addNotification` on that instance.

Feel free to clone the repo and play with the samples to see you're not tied to `onClick` event.

**Comment by yashshukla1912** [comment]
Thanks for your support @teodosii , it worked but now if i want to load a spinner when a page gets rendered, i get `this.notificationDOMRef.current as null`. I took help of this link https://stackoverflow.com/a/50019873 where i came to know **Refs don’t get set for elements that weren’t rendered** but here i want to show loader and success message(notification). i am sharing code, will you please help me out in this error as I am new to react.
![ss](https://user-images.githubusercontent.com/51371310/61687748-c2d8a180-ad40-11e9-9a62-201dc077bb6d.png)

**Comment by teodosii** [comment]
You want to show both loader and the success notification? These are React related topics, not package related, and it's not really clear for me what you want to achieve. First of all, as the documentation says, you should have the `react-notification-component` at the top of the DOM tree, not in every component you're using it.

As long as you set a ref to the component, you should be able to call `addNotification` and `removeNotification` on that ref instance. It's React related and has nothing to do with the package itself.
