### ISSUE TITLE
Blog post

### ISSUE THREAD

**Issue by wle8300** [teodosii/react-notifications-component#27]
Hi @teodosii!

This isn't really an issue. I just wanted to let u know that I did a blog post on this library: https://alligator.io/react/react-notifications-component/

Thx for the great work on this!

**Comment by teodosii** [comment]
Haha, did not expect this! That's a great detailed post there. Thanks, you made my day 😄 

Just a quick mention, under the hood it does not use Context API, but it works basically in the same way.

**Comment by wle8300** [comment]
Happy to share this with others. You went the extra mile with this lib!

Does it use redux? Or your own state management?

**Comment by teodosii** [comment]
No, it doesn't use redux. It relies on that fact that you need one instance only per app and when it gets mounted it creates the store you import to add and remove notifications. Simple as that, no redux, no context.
