### ISSUE TITLE
Pass classname and id to notification component

### ISSUE THREAD

**Issue by sradevski** [teodosii/react-notifications-component#30]
This is useful when you want to override the styling of the notification containers using something like `styled-components` without relying on `.css` files. For example, if you pass the className, you can do the following:

``` javascript
const StyledContainer = styled(ReactNotification)`
	.react-notification-root .notification-item {
		box-shadow: none;
	}
`
```
but `styled-components` rely on the component passing the classname to the underlying tag.

**Comment by teodosii** [comment]
Commented in the PR, closing the issue
