### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by brandondurham** [teodosii/react-notifications-component#34]
I have a situation where I need to list three short things on their own lines. Doesn’t look like there is Markdown support. Is that on the docket?

**Comment by teodosii** [comment]
You mean to render custom markdown content? You'll need a react markdown library for that. Or did I miss your question?

**Comment by brandondurham** [comment]
I mean inside the message property. Looking to have markdown in there for mild (but important) formatting.

**Comment by brandondurham** [comment]
Thank you!
