### ISSUE TITLE
dismiss -> onscreen | Option is ignored if content is set

### ISSUE THREAD

**Issue by KarenK123** [teodosii/react-notifications-component#37]
onScreen option is ignored if content is set

**Comment by teodosii** [comment]
Indeed is ignored, at that point I decided it would be best to strip it if `content` is used. But having issue #35 where I have to supply `id` to custom content, I might supply an `animationPlayState` to mimic the behavior when using normal notifications. Although you will still have to add some logic to handle prop change and play/stop the existing animation which you will need to provide to custom content. At this point I don't know if it's worth adding it or not.

**Comment by teodosii** [comment]
Added `animationPlayState` to supplied props when using `content`. You will still need to handle prop change on `animationPlayState` and play or stop the animation accordingly.

Fix was done in `v2.2.0`
