### ISSUE TITLE
Custom Notification UI

### ISSUE THREAD

**Issue by akhilpanchal** [teodosii/react-notifications-component#39]
Hi:
I am investigating this library for my use-case.
I have a React component that represents the UI for the notification along with the animations while mounting and unmounting. Is there a way I can render my component as a notification using the existing API?

**Comment by teodosii** [comment]
I'll tell you if you answer honestly - have you even checked the `README`? :laughing:

Now if you had spent at least 1 minute skimming the `README` you'd have noticed that we support custom content usage - meaning you render anything you want.
Now in terms of mounting and unmount animations, it depends. 

If it's CSS animation, it will work, you just need to provide the classes.
If it's JS (e.g. animations based on `requestAnimationFrame`) it might work or not, haven't tried and I can't tell for sure.

**Comment by akhilpanchal** [comment]
Hey I apologize! I guess I directly jumped across to look at example code of custom UI and missed the feature list at the very top. I shouldn't have hurried. My bad.
