### ISSUE TITLE
pauseOnHover with custom content

### ISSUE THREAD

**Issue by akhilpanchal** [teodosii/react-notifications-component#41]
Thanks for this really awesome library :).

The pauseOnHover feature works as expected when we dont have a `content` option in the `store.addNotification` call.
I am trying to make the pauseOnHover feature work for a custom notification content.

Here is a [codesandbox link](https://codesandbox.io/s/notif-comp-pauseonhover-custom-content-igdn6).

Can you let me know if I am missing something?

**Comment by teodosii** [comment]
Hey, thanks for feedback.
Someone raised this question a few months ago as well, unfortunately `pauseOnHover` is not supported when used together with `content`.

At this point I don't know wether I will add this functionality or not. It's not the kind of option that you'd benefit easily/out of the box if implemented. When using `content` you'd need to manually set `onAnimationEnd` for timer and to update timer's style according to props change. Would be easier to have all that handling done by yourself when using content than having the library do it, at least that's my opinion.

**Comment by teodosii** [comment]
Oh, my bad. I thought you said about `onScreen`. Will do a push to support `pauseOnHover`

**Comment by oyemeLife** [comment]
@teodosii thanks, I miss that functionality too!

**Comment by teodosii** [comment]
#41 fixed in `2.3.0`

**Comment by oyemeLife** [comment]
Really big thanks for the fixing that issue.
