### ISSUE TITLE
Multi-line notification message

### ISSUE THREAD

**Issue by mendeel** [teodosii/react-notifications-component#42]
Hello everyone!

I need to send a notification with a relatively long message or containing a list of items but as the message gets longer, the width of the notification gets bigger, it doesn't create line breaks neither allows me to create a linebreak by myself on the message content.

Is it possible to do this linebreak or put custom HTML in the message? Something like this.

Thanks for the help!

**Comment by teodosii** [comment]
Hey, use `content` property for more control over the notification's output.

**Comment by teodosii** [comment]
Will close this issue as README is describing usage of `content` quite well

**Comment by mendeel** [comment]
Sorry to bother but the README.md I'm reading only states this:
"Custom notification content, must be either Class Component, Functional Component or React element. If being supplied as functional or class component, id will be supplied as prop"

Does this mean I'll have to supply the full notification HTML? I wanted to use the default themes as they're pretty, but with custom message formatting.

**Comment by teodosii** [comment]
Don't worry, you're not bothering, I just hate having open issues.
At the time being HTML content is not supported when used with `message`. Although it should support this, at the time of writing the library it didn't occur to me to think of all possible scenarios.
Will let it open and I might do a quick fix to support that as well

**Comment by teodosii** [comment]
For now, I'd say stick to custom content and just copy the classes used by default notifications. It's not adding much code and it's not difficult either. I can't give an estimate on when this is gonna be ready ;(

**Comment by mendeel** [comment]
Hmm your explanation helped a lot! Don't worry, you can keep it closed if you want too :D

Thanks and congratulations for your work!

**Comment by kanji-stack-dev** [comment]
i am using server side validation in one notification. but when i am add
tag between two validation errors. so
tag display in notify error. what i can do??

my react js code:-
const data = new FormData(event.target);
axios.post('http://localhost/practice/laravel/laravel_api/api/product_add', data)
.then(function (response) {
if (response.data.status == false){
var erorrs = '';
response.data.message.map(function(erorr){
erorrs += erorr+"
";
});
store.addNotification({
title: "Error",
message: erorrs,
type: "danger",
insert: "top",
container: "top-right",
animationIn: ["animated", "fadeIn"],
animationOut: ["animated", "fadeOut"],
width: 350,
dismiss: {
duration: 5000,
onScreen: true,
pauseOnHover: true,
showIcon: true,
}
});
}
});

**Comment by teodosii** [comment]
#42 fixed in `2.3.0`. Now both `title` and `message` supports custom content - a React node or a function.
