### ISSUE TITLE
Notification Never Dismisses 

### ISSUE THREAD

**Issue by DivyanshBatham** [teodosii/react-notifications-component#43]
Not sure if this is a feature or bug. I just found it and am in a hurry to complete some work, hence not digging deep and just posting here.

Once the notification is open:
```
store.addNotification({
  title: "Wonderful!",
  message: "teodosii@react-notifications-component",
  type: "success",
  insert: "top",
  container: "top-right",
  animationIn: ["animated", "fadeIn"],
  animationOut: ["animated", "fadeOut"],
  dismiss: {
    duration: 5000,
    onScreen: true
  }
});
```

If you keep resizing the window, before the time ends it'll keep on going.

**Comment by teodosii** [comment]
How much are you actually resizing? Are you changing from desktop to mobile view or vice versa? If so, I see that timer is reset due to re-rendering and setting the whole duration - which is a bug - but it never happened to me not to get dismissed.

**Comment by DivyanshBatham** [comment]
@teodosii Sorry for a late reply, Yeah I was resizing from desktop to mobile and vice-versa.

**Comment by teodosii** [comment]
For now, I'm not going to implement any fix for this. When changing from one view to the other (e.g. mobile to desktop) containers get rendered again and hence the duration will be the original one.
