### ISSUE TITLE
Multi-line in one notification

### ISSUE THREAD

**Issue by kanji-stack-dev** [teodosii/react-notifications-component#45]
i am using server side validation in one notification.  but when i am add <br> tag between two validation errors. so <br> tag display in notify error. what i can do??

my react js code:-
const data = new FormData(event.target);
            axios.post('http://localhost/practice/laravel/laravel_api/api/product_add', data)
                .then(function (response) {
                    if (response.data.status == false){
                        var erorrs = '';
                        response.data.message.map(function(erorr){
                            erorrs += erorr+"<br>";
                        });
                        store.addNotification({
                            title: "Error",
                            message: erorrs,
                            type: "danger",
                            insert: "top",
                            container: "top-right",
                            animationIn: ["animated", "fadeIn"],
                            animationOut: ["animated", "fadeOut"],
                            width: 350,
                            dismiss: {
                                duration: 5000,
                                onScreen: true,
                                pauseOnHover: true,
                                showIcon: true,
                            }
                        });
                    }
                });

**Comment by teodosii** [comment]
There's an open ticket for that already #42
