### ISSUE TITLE
Can we add custom style?

### ISSUE THREAD

**Issue by dashName** [teodosii/react-notifications-component#47]
I want to position the notification containers..is it possible to provide margin / padding etc?

**Comment by teodosii** [comment]
I did not get your question, could you be more precise? What do you mean by positioning the notification containers?

**Comment by dashName** [comment]
> I did not get your question, could you be more precise? What do you mean by positioning the notification containers?

let say i want to show list of notifications under a bell icon.so i want to change the style of the container.

**Comment by teodosii** [comment]
No, we're not supporting such things at the moment. Most likely it will never be supported.
