### ISSUE TITLE
Question: is there a way to hide the timer?

### ISSUE THREAD

**Issue by raymond-ong** [teodosii/react-notifications-component#48]
Great library, but I find the timer (progress bar) distracting to the user so I want to hide it.
I can manually hide the timer by adding my own CSS like so:
```
.notification-item .timer {
    visibility: hidden;
    margin-top: 0px !important;
}
```
If I set it to `display:none`, the notification never dismisses.
Is there a props or something to hide the timer, so that i don't need to override the CSS?

**Comment by teodosii** [comment]
What were the options when creating the notification? The timer is being shown if `dismiss. onScreen` is set to true, which defaults to false.

**Comment by teodosii** [comment]
Until further clarifications I will have this ticket closed. If it's a bug we'll reopen it afterwards.

**Comment by raymond-ong** [comment]
Hi @teodosii !!
Thanks for the reply. You can close it now.
Yeah, this is just the onScreen prop!
Stupid me :-)
