### ISSUE TITLE
How can I add custom contents like the success message with icon ?

### ISSUE THREAD

**Issue by RafaaBelhedi** [teodosii/react-notifications-component#49]
How can I add custom contents like the success message with icon ?
I can only ad the 5 types (danger,success,etc...)

**Comment by teodosii** [comment]
[Examples on GitHub](https://github.com/teodosii/react-notifications-component/tree/master/samples/js/components/examples)

**Comment by barakjobs** [comment]
How can we customize the notification bar with icon and color. Can you please help on this.
![image](https://user-images.githubusercontent.com/50011656/103460787-2d1bb100-4d3f-11eb-935d-140073ed2a0c.png)
