### ISSUE TITLE
Installation failed via yarn

### ISSUE THREAD

**Issue by suraneti** [teodosii/react-notifications-component#50]
**Reproduce**

`yarn add react-notifications-component`

```
error /Users/suraneti/Thanks-Dashboard/node_modules/react-notifications-component: Command failed.
Exit code: 1
Command: npx npm-force-resolutions
Arguments: 
Directory: /Users/suraneti/Thanks-Dashboard/node_modules/react-notifications-component
Output:
npx: installed 5 in 1.661s
ENOENT: no such file or directory, open './package-lock.json'
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Edit**
1. Install success via yarn with version `2.0.7`.

**Comment by teodosii** [comment]
Oh, I added `npm-force-resolutions` to fix a vulnerability on a dependency until it gets fixed by maintainers. I suggest you use `2.2.4` istead of `2.0.7`

**Comment by masbaehr** [comment]
Same issue with NPM

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-notifications-component@2.2.5 preinstall: `npx npm-force-resolutions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-notifications-component@2.2.5 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:


Ignored the update for now. Please provide instructions how to fix if possible. Thanks

**Comment by Grosscorp** [comment]
Same problem.

**Comment by oyemeLife** [comment]
2.2.4 works fine for me
"react-notifications-component": "2.2.4"

**Comment by teodosii** [comment]
`2.2.7` should work now
