### ISSUE TITLE
CSS theme not being applied to the component

### ISSUE THREAD

**Issue by antonioiliev** [teodosii/react-notifications-component#51]
Just tried to setup the component and it works, however, no CSS is applied.

My setup looks like this:
```jsx
import ReactNotification from 'react-notifications-component';
import { store } from 'react-notifications-component';
import notificationStyles from 'react-notifications-component/dist/theme.css';
```

And a simplified component example - 
```jsx
const Header = props => {
  React.useEffect(() => {
    store.addNotification({
      title: "Wonderful!",
      message: "Test message",
      type: "info",
      insert: "bottom",
      container: "bottom-right",
      animationIn: ["animated", "fadeIn"],
      animationOut: ["animated", "fadeOut"],
      dismiss: {
        duration: 5000,
        onScreen: true
      }
    });
  }, []);
return (
    <div>
      <ReactNotification />
    </div>
);
```

When I console.log the notificationStyles variable I can see the styles - 
![react-notifications](https://user-images.githubusercontent.com/33114585/72889209-d2e53400-3d17-11ea-8638-c3ed5f7ad815.jpg)

I am not sure what I might be doing wrong. Any suggestions will be appreciated!!!

**Comment by teodosii** [comment]
You're scoping CSS classes and that's why it's not working.

**Comment by antonioiliev** [comment]
Thank you for the quick response @teodosii.

What do you mean by scoping CSS classes?

Initially, I did follow the instructions and imported the theme css file in both the 'Header' component and in the 'App' component via this line of code - 
`import 'react-notifications-component/dist/theme.css';
`
This did not work, that is why I tried to find out whether the css classes are being loaded at all.  Turns out the correct file had been imported, however, the css is still not being applied to the notifications.

**Comment by teodosii** [comment]
I don't know what you're using behind the scene but this line should scope your classes

```css
import notificationStyles from 'react-notifications-component/dist/theme.css';
```

Also from your console.log you've shared it's clearly showing that each class gets scoped, e.g. `theme__notification-container-top-left__3A-vy`. Should've been `notification-container-top-left`.

The only way of making it work is to import it in the standard way

```css
import 'react-notifications-component/dist/theme.css';
```

Which works as no one else complained about that. You'll need to figure it out by yourself as I do not have enough details to help you - is the file loaded by the browser? does `react-notifications-component` append CSS classes correctly when you inspect the DOM?

**Comment by antonioiliev** [comment]
You were right. The problem was webpack`s css-loader config. It was set to scope class names.

`{
            loader: 'css-loader',
            options: {
              modules: false, // instead of true
              sourceMap: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]__[hash:base64:5]'
            }
          }`
