### ISSUE TITLE
Swipe to close not working

### ISSUE THREAD

**Issue by moh3n9595** [teodosii/react-notifications-component#52]
Swiping to close notification with touch not working in `react-notifications-component@v2.2.1`

**Comment by teodosii** [comment]
Fixed #52 in `2.3.0`

**Comment by moh3n9595** [comment]
still issue is here!

**Comment by teodosii** [comment]
Haven't seen the notification, you should have reopened the issue. Will have a look

**Comment by teodosii** [comment]
From what I've debugged, on tablets and such the issue was there. I've updated the handling for touch. Please have a look and come back with an answer whether it fixed your problem or not.

Fix was done in `2.4.0`
