### ISSUE TITLE
Sliding Exit and enter not working

### ISSUE THREAD

**Issue by ashishnagpal2498** [teodosii/react-notifications-component#53]

**Comment by teodosii** [comment]
Need code to illustrate the issue, otherwise I'll consider it invalid and will close it.

**Comment by ashishnagpal2498** [comment]
store.addNotification({
      title: "",
      message: "Hello"
      type: "success"
      insert: "top",
      width:400,
      container: "top-right",
      animationIn: ["animated", "fadeIn"],
      animationOut: ["animated", "fadeOut"],
      slidingExit: {
        duration: 800,
        timingFunction: 'ease-out',
        delay: 0
      },
      slidingEnter:{
        duration: 1000,
        timingFunction: "ease-in",
        delay:0
      },
      dismiss: {
        duration: 5000,
        showIcon: true
      }
    })
I applied the entry and exit transition but it only fades.

**Comment by teodosii** [comment]
Will look into it.

**Comment by teodosii** [comment]
What exactly do you want to accomplish here? `slidingEnter` is used when notifications are being added, you control that transition, not animation. Animations are fade in, fade out - as in your example. It's not taking into consideration your duration at all for the transition?
