### ISSUE TITLE
Feature: set max count

### ISSUE THREAD

**Issue by zhaoyao91** [teodosii/react-notifications-component#54]
it would be nice if we could set the max count of notifications

**Comment by teodosii** [comment]
That could be handled by the developer using the library, I don't see any benefit for this. At most we could expose a helper to let you know how many notifications are currently on the screen, but this can also be accomplished by the developer.

**Comment by masbaehr** [comment]
I came across this problem as well. Of course it would be possible to do this by the developer, however it would mean to create a variable , keep count of the notification et cetera. (If you think about it, many things could be handled by the developer even color :P ) But it would be very useful to do this 

<ReactNotification maxNotifications={4} />

And automagically there are never more than 4 notifications active, the oldest will be pushed away instantly.

Other similar libs do it as well: https://fkhadra.github.io/react-toastify/introduction/ 

So i also think this would be a valid feature request - which is not urgent - but still worth to be kept open!
