### ISSUE TITLE
jsdoc/typehinting for code intellisense?

### ISSUE THREAD

**Issue by mdecurtins** [teodosii/react-notifications-component#59]
Hi,

Great library, thank you! Would like to suggest an enhancement to allow IDEs like VSCode to provide IntelliSense for your API. Right now the code works but type hinting is lacking, so `addNotification` for example shows up as `any`:

![image](https://user-images.githubusercontent.com/13541242/77108157-1e564e80-69f8-11ea-831b-15e631e6e7ec.png)

**Comment by teodosii** [comment]
Will add typescript support, closing this ticket as there's one for TS.
