### ISSUE TITLE
Lack of top-center position and onDismiss event

### ISSUE THREAD

**Issue by hiredgun** [teodosii/react-notifications-component#6]
Any ETA for onDismiss event and top-center position. I wanted to use this component in my project but without those, I have to find sth else.

**Comment by teodosii** [comment]
By `onDimiss` you mean the moment when removal is triggered or when the notification is fully removed? 

If I have enough time there's a chance I'll publish `v0.1.1` having these changes by the end of this week, worst case would be 3 weeks from now.

**Comment by hiredgun** [comment]
I meant the moment when a notification is fully removed.

**Comment by teodosii** [comment]
Unfortunately this will be delayed due to lack of time. Can't give anymore an estimate for this

**Comment by teodosii** [comment]
Feature has been implemented - both top and bottom center containers have been added to the component. Use `onNotificationRemoval` callback to see when notification is removed. Open another issue if there are any bugs.
