### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'isReactComponent' of undefined

### ISSUE THREAD

**Issue by spawn-guy** [teodosii/react-notifications-component#61]
I just updated library version from 2.0.7 to 2.4.0 and started getting the error in title.

> Unhandled Rejection (TypeError): Cannot read property 'isReactComponent' of undefined
/src/utils/validators.js:12 (or here https://github.com/teodosii/react-notifications-component/blob/master/src/utils/validators.js#L12)

i've found some other discussion in a different component that looks similar. there is a fix there and some explanation.
https://github.com/tannerlinsley/react-table/issues/1502
https://github.com/tannerlinsley/react-table/pull/1503

i am not sure if it helps to solve anything or i am having different issues. 
if needed - i can make Pull-Request here.

for now i will roll back to the old version

**Comment by teodosii** [comment]
Fixed in `3.0.0`
