### ISSUE TITLE
Ability to have default options for notifications like react-toastify

### ISSUE THREAD

**Issue by douglasrcjames** [teodosii/react-notifications-component#62]
I want to switch over to this library from react-toastify, but my only worry is that there isn't a way to set options for notifications throughout the project. Is there an easy way to just set options like duration and positioning in root index like how toastify does? 

**react-toastify:**
```
// App.js
<ToastContainer
   position="top-right"
   autoClose={5000}
   hideProgressBar={false}
   newestOnTop={false}
   closeOnClick
   />

// Calling an alert in component
toast.warn("Please sign in.")
```

**react-notifications-component:**
```
// App.js
<ReactNotification />

// Calling an alert in component
store.addNotification({
  title: "Wonderful!",
  message: "teodosii@react-notifications-component",
  type: "success",
  insert: "top",
  container: "top-right",
  animationIn: ["animated", "fadeIn"],
  animationOut: ["animated", "fadeOut"],
  dismiss: {
    duration: 5000,
    onScreen: true
  }
});
```

**Comment by teodosii** [comment]
No, we do not have any predefined config atm, but sounds like a good feature to have.

**Comment by douglasrcjames** [comment]
No worries, love the library though! I'll keep an eye out for this implementation from the library in the future.
