### ISSUE TITLE
Rendering bottom-center on mobile cuts the message off

### ISSUE THREAD

**Issue by ryanrdetzel** [teodosii/react-notifications-component#63]
Reproducible in the browser (Chrome mobile testing) and on an iPhone.

**Comment by ryanrdetzel** [comment]
`.notification-container-mobile-bottom {
    margin-bottom: 25px;
}`

Fixes the issue but there might be a better way

**Comment by teodosii** [comment]
Could you post a screenshot? I was not able to reproduce it on github pages.

**Comment by ryanrdetzel** [comment]
![react-notifications](https://user-images.githubusercontent.com/79599/77850365-04f39600-71a0-11ea-8fe1-73656f2a2b8d.JPG)

**Comment by teodosii** [comment]
Can you have a look at `3.0.0`? It's also published to github pages, there the notification is positioned properly.
