### ISSUE TITLE
Reactive component inside the notification (message) ?

### ISSUE THREAD

**Issue by Vaneste** [teodosii/react-notifications-component#64]
First things first, thanks a lot for this great component !

This is more a feature question not an issue but as message option accepts a React component, I wonder if it's possible to make this component re-rendering during notification ?
Ex: displaying a progress bar for some processing task...

Thanks !

**Comment by teodosii** [comment]
You could use custom content to customise notification the way you want it. As for message you could use a functional component with a prop to let it know whether it should render progress bar or something else. Have you tried it this way? It won't accept a React component for message form what I remember, but you're allowed to use functional components or React nodes.
