### ISSUE TITLE
Any typescript support?

### ISSUE THREAD

**Issue by FrozenFury** [teodosii/react-notifications-component#65]

**Comment by teodosii** [comment]
I can't say for now, I'll let it open.

**Comment by SarhadSalam** [comment]
This is my first time writing a typescript definition file for an external library, but I have worked with typescript for a while.

Seems like there is only 2 publicly accessible API method, do you mind if I make a PR and create a type binding for this?

**Comment by teodosii** [comment]
@SarhadSalam Sure, I will merge the PR when it's available

**Comment by SarhadSalam** [comment]
@teodosii I actually created a type definition at DefinitelyTyped since I needed it in my project. I will update the readme and include installations instructions!

**Comment by teodosii** [comment]
Next version is scheduled for the next days, will have typescript included! :partying_face:

**Comment by gretzke** [comment]
> Next version is scheduled for the next days, will have typescript included! 🥳

Is this version 2.4.1? The typings by @SarhadSalam give me an error while creating a new custom type like this:

`<ReactNotification types={[{ htmlClasses: ['test-notification'], name: 'test' }]} />`

How can I enable typescrip support on the latest version?

**Comment by teodosii** [comment]
Fixed in `3.0.0`. Let me know if there's an issue but there should be all the bindings included in the NPM package.
