### ISSUE TITLE
Updating doc or adding v4 support for animate.css

### ISSUE THREAD

**Issue by CorfitzMe** [teodosii/react-notifications-component#71]
Animate.css came around with breaking changes, that messed up the implementation. You either have to import the `animate.compat.css` package or install a `3.X.X` version in order to support animated notifications as all animated classes are prefixed `animate__` from v4 of Animate.css.

My suggestion would be to add a note to the animate documentation about the matter in the `README` file.

## Solution 1:
```
$: yarn add animate.css
--
import 'animate.css/animate.compat.css' // Backwards compatibility
```

## Solution 2:
```
$: yarn add animate.css@3.7.2
--
import 'animate.css/animate.css'
```

**Comment by teodosii** [comment]
Done, thanks for letting me know.
