### ISSUE TITLE
Warning in postcss while building | Prefix-less CSS

### ISSUE THREAD

**Issue by masbaehr** [teodosii/react-notifications-component#72]
Not really sure where this comes from, but i got this while building a react next.js app where i use react-notifications-component. This is not something critical - just mentioning it :) 

Greetings, time traveller. We are in the golden age of prefix-less CSS, where Autoprefixer is no longer needed for your stylesheet.

./node_modules/react-notifications-component/dist/theme.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-5-1!./node_modules/next/dist/compiled/postcss-loader??__nextjs_postcss!./node_modules/react-notifications-component/dist/theme.css)
Warning

**Comment by teodosii** [comment]
Is it showing this warning only for this library or are you getting this for other dependencies as well? I can't figure out what's the cause for this. I haven't noticed any prefixed properties in that file. Also, that file is a theme for the site project, why are you building the site project?
