### ISSUE TITLE
Breaking change from animte.css affecting notification animations 

### ISSUE THREAD

**Issue by solomonakp** [teodosii/react-notifications-component#75]
hello @teodosii setting up notification was a breeze thanks to your detailed documentation. But setting up Animate.css with the current documentation examples/samples took a toll on me due to breaking changes from Animate.css. I had to go through their documentation to notice the  version migration breaking changes and addition of a new prefix when wasn't specified anywhere on your this repo. To get the animations to work i had to import the animte.css/animate.compat.css instead of the regular  animte.css/animate.min.css due to the breaking change. I would suggest documentation : 

-  should be updated accordingly to notify change since this library is dependent on animate.css

-  should be adjusted  to conform with their breaking change .

![image](https://user-images.githubusercontent.com/44111113/87859012-0bae4080-c92a-11ea-8714-e769120f7b5f.png)

**Also it would also help to specify what each index of the animation array does for animationIn and animationOut in the event users decide to include their own animations**

thanks. wonderful alert component you got here... I think I would try tweenful too

**Comment by teodosii** [comment]
Hey @solomonakp 

`animate.css` is not a dependency for `react-notifications-component`. It is used on github pages just to illustrate usage with icons, but other than that it's not tied to it. 

Could you please make a PR to have README updated? It's not an urgent thing, I'll have this issue closed for now and later on we'll have README updated.

**Comment by teodosii** [comment]
Actually I've done it myself.
