### ISSUE TITLE
Error "window is not defined" in Server-side Rendering

### ISSUE THREAD

**Issue by piglovesyou** [teodosii/react-notifications-component#8]
Hi. The component implementation does not seem to assume server-side rendering.

https://github.com/teodosii/react-notifications-component/blob/master/src/react-notification-component.js#L28

```
ReferenceError: window is not defined
```

**Comment by teodosii** [comment]
Thanks for reporting the issue. I will fix that and publish a new version soon

**Comment by teodosii** [comment]
Issue has been fixed. Could you also check to see if it's working? Try with latest NPM publish

**Comment by piglovesyou** [comment]
Nice, but I cannot promise I'll verify it sorry
