### ISSUE TITLE
We need an API (Prop) for automatically clearing the notification on duration end.

### ISSUE THREAD

**Issue by ivanjeremic** [teodosii/react-notifications-component#81]
Like said in the title We need an API (Prop) for automatically clearing the notification on duration end. 
Is there some helpful hook for doing this for now?

Ps. I see lots of Class Components used in the sample and this library. (Classes are out). Hooks are where the focus should be.

**Comment by teodosii** [comment]
Classes are not out, I don't know who told you that, he clearly informed you wrong.
Also your question doesn't make much sense, do you want to subscribe to notification's removal or is there some bug you're speaking about? Notifications *are* cleared automatically at the end. For subscribing, there is `onNotificationRemoval`

**Comment by ivanjeremic** [comment]
> Classes are clearly not out, I don't know who told you that, he clearly informed you wrong.
> Also your question doesn't make much sense, do you want to subscribe to notification's removal or is there some bug you're speaking about? Notifications _are_ cleared automatically at the end. For subscribing, there is `onNotificationRemoval`

Keep out writing your Classes you are clearly wrong informed, I know learning new things is depressing sometimes but at least try it.
