### ISSUE TITLE
How to close all Notifications at Once without passing id.

### ISSUE THREAD

**Issue by Abhinay1235** [teodosii/react-notifications-component#82]
How to close all Notifications at Once without passing id.

**Comment by teodosii** [comment]
Will publish next days a new version, will have this included. So far nobody asked for `closeAllNotifications`, hence it was never included.

**Comment by sabarezaief** [comment]
Hi, When will the new version be released? I need a new version with these features

**Comment by teodosii** [comment]
Fixed in `3.0.0`
