### ISSUE TITLE
Problem with adding notification. Error 'this.add is not a function'

### ISSUE THREAD

**Issue by Jammmes** [teodosii/react-notifications-component#86]
Hi, help me please, here are my steps:

0. `npm install --save-dev @types/react-notifications-component
npm install react-notifications-component`

1. My App uses redux
```jsx
// index.ts
...
render(<Provider store={store} context={ReactReduxContext}>
          <PersistGate loading={null} persistor={persistor}>
            <ConnectedRouter history={history} context={ReactReduxContext}>
              <App />
            </ConnectedRouter>
          </PersistGate>
        </Provider>
, document.getElementById('reactContainer'));
```

2. I placed <ReactNotification /> in the App like
// App.tsx
import ReactNotificationfrom 'react-notifications-component';
```jsx
const App = () => {
  return (
    <>
      <ReactNotification />
      <OtherComponent1/>
      <OtherComponent2/>
    </>
  )
};
```

3. In the <OtherComponent1/> I imported store, then I tried to add notification.
```jsx
// OtherComponent1.tsx
import React, { FunctionComponent } from 'react';
import { ReactNotificationOptions, store } from 'react-notifications-component';
export const OtherComponent1: FunctionComponent = () => {
store.addNotification({
  title: "Wonderful!",
  message: "teodosii@react-notifications-component",
  type: "success",
  insert: "top",
  container: "top-right",
  animationIn: ["animate__animated", "animate__fadeIn"],
  animationOut: ["animate__animated", "animate__fadeOut"],
  dismiss: {
    duration: 5000,
    onScreen: true
  }
});
  return <>Hello</>;
};
```

4. After that I got the error: 
`react-notifications.dev.js:614 Uncaught TypeError: this.add is not a function
    at Store.push../node_modules/react-notifications-component/dist/js/react-notifications.dev.js.module.exports../src/store/index.ts.Store.addNotification (react-notifications.dev.js:614)`

**Comment by teodosii** [comment]
Might be because you're using the old typings for TypeScript. They're no longer needed since the project is now written in TS. Try without the typings.

Haven't tried yet with TS but package works with CRA.

**Comment by fnpen** [comment]
@Jammmes You should check:

```
if (store.add !== null) {
    store.addNotification({
```

It looks like a call before registration: 
https://github.com/teodosii/react-notifications-component/blob/master/src/store/index.ts#L63
class clears it in the constructor:  https://github.com/teodosii/react-notifications-component/blob/master/src/store/index.ts#L22
but uses it without checking: https://github.com/teodosii/react-notifications-component/blob/master/src/store/index.ts#L49

Maybe it is the issue or wrong execution flow(add before mount/registration).

**Comment by teodosii** [comment]
Oh yea, didn't notice that, you shouldn't call `addNotification` inside render (be it class or method - use `cDm` or `useEffect`) !!! ⚠️⚠️⚠️⚠️⚠️

**Comment by masbaehr** [comment]
Getting this error recently on a code which was working fine before. 
The call is being made in useEffect

useEffect(() => {
    store.addNotification( {..})
  }, []);

![image](https://user-images.githubusercontent.com/38694044/118108693-96dc5380-b3e0-11eb-9231-71f3c188ac96.png)
