### ISSUE TITLE
SyntaxError: Duplicate parameter 'title' not allowed in function with destructuring parameters.

### ISSUE THREAD

**Issue by imCorfitz** [teodosii/react-notifications-component#88]
Creating a clean repo using https://github.com/jpedroschmitz/typescript-nextjs-starter

Then all I did was to install the packages `react-notifications-component` `animate.css` and `-D @types/react-notifications-component`, and create an `_app.tsx` file where I included the `<ReactNotificationsComponent />`.

```tsx
import 'animate.css/animate.min.css';
import '../../styles/notifications.scss';
import ReactNotificationsComponent from 'react-notifications-component';

function App({ Component, pageProps }) {
  return (
    <>
      <Component {...pageProps} />
      <ReactNotificationsComponent />
    </>
  );
}

export default App;

```

PS. The `@types` are outdated since `3.0.0` release

![Screenshot 2020-11-21 at 10 47 23](https://user-images.githubusercontent.com/52371939/99875376-ffdbcf00-2be6-11eb-94b0-bdf547712bf1.png)

**Comment by teodosii** [comment]
Was fixed in a PR, just released `3.0.3`
