### ISSUE TITLE
Loss of obj.type with Content

### ISSUE THREAD

**Issue by dmayo2** [teodosii/react-notifications-component#9]
Why does `obj.type` become undefined (ignored) when `obj.content` is true? I understand the ability of totally customizing the notification.

I'm trying to have valid html in the `notification-message`. The `obj.message` will not allow anything but string, and I'd rather not use `dangerouslySetInnerHTML`. So, I'm passing `obj.content` with a valid jsx object `content: (<p className="notification-message">Hello<br />World</p>)` 

Everything works fine, except that `obj.type` is set to `undefined`. I'd like to use the included CSS for types (success, danger, default, info, warning), but the codebase seems to remove even any custom classNames that use one of those type. Just wondering why the decision was made to ignore `obj.type`?

Thanks

**Comment by teodosii** [comment]
Because when using custom content you're supposed to have full control over the rendered content and ignore default structure - that was my thinking when I've written the library.

I haven't tried it but I think you can still use the built-in types even with custom content, you'll just need to wrap your content with the needed classes.

Have you tried this approach?

**Comment by dmayo2** [comment]
That's sound reasoning. So maybe a feature request? Maybe only ignore the default structure if `type:custom` ?

I have tried to use the built in classes (why re-invent the wheel) and the class with the type is always stripped out of the final result. Even if I hard code `notification-custom-success`, that get's stripped out. (sorry bad formatting)

`addNotification(obj){`
`    const defaultObj = {`
`		insert: "top",`
`		container: "top-right",`
`		animationIn: ["animated", "fadeIn"],`
`		animationOut: ["animated", "fadeOut"],`
`		dismiss: { duration: 0 },`
`		dismissable: {click: true}`
`	}`
`		if( obj.hasOwnProperty("content") === true ){`
`			let tempType = 'notification-item notification-custom-' + obj.type + ' ' + defaultObj.animationIn[0] + ' ' + defaultObj.animationIn[1] + ' notification-item-child'`
`			let tempContent = (`
`				<div className={tempType}>`
`					<div className="notification-content">`
`						<div className="notification-close"><span>x</span></div>`
`						<h4 className="notification-title"></h4>`
`						{obj.content}`
`					</div>`
`				</div>`
`			)`
`			obj.content = tempContent`
`		}`
`		let newObj = {...defaultObj, ...obj}`
`		this.notificationDOMRef.current.addNotification(newObj)`
`	}`

**Comment by teodosii** [comment]
Looks like you're doing it wrong. I've tried now on `samples`, just modified `CustomContentExample` with the following

```jsx
this.props.addNotification(Object.assign({}, notification, {
  width: 275,
  container: getContainer(),
  content: (
    <div className="notification-item notification-success notification-item-child">
      <div className="notification-content">
        <div className="notification-close">
          <span>×</span>
        </div>
        <h4 className="notification-title">Aww!</h4>
        <p className="notification-message">Everything is possible with react-notifications-component</p>
      </div>
    </div>
  )
}));
```

And it's displaying the notification using the success type properly. So there's no reason to add an unnecessary feature to the component. You were using the wrong classes.

See if this helped you, it worked for me so there shouldn't be any problem. I'll close this shortly after.

**Comment by dmayo2** [comment]
Thanks. I'll give it a try. (I may have provided not exact classes, as I was trying a number of things to get it work.
