### ISSUE TITLE
Typescript Error: 'swipe' does not exist in type 'TransitionOptions'

### ISSUE THREAD

**Issue by kennedykori** [teodosii/react-notifications-component#92]
According to the `README`, `touchSlidingExit` has 2 nested transition so the following options(taken from the `README`) should work:
```typescript
{
    // ... Other options
    touchSlidingExit: {
        swipe: {
            duration: 400,
            timingFunction: 'ease-out',
            delay: 0
        },
        fade: {
            duration: 400,
            timingFunction: 'ease-out',
            delay: 0
    }
}
```
But instead, I get the following error: `Type '{ swipe: { duration: number; timingFunction: string; delay: number; }; fade: { duration: number; timingFunction: string; delay: number; }; }' is not assignable to type 'TransitionOptions'.
  Object literal may only specify known properties, and 'swipe' does not exist in type 'TransitionOptions'.`

I am using the following dependencies:
```json
{
    "dependencies": {
        "react-notifications-component": "^3.0.2"
    },
    "devDependencies": {
        "@types/react-notifications-component": "^2.4.0"
    }
}
```

**Comment by kennedykori** [comment]
The typings for the notification options are defined as:
```typescript
export interface ReactNotificationOptions {
    // ...Other properties
    touchSlidingExit?: TransitionOptions;
}
```

Shouldn't it rather be:
```typescript
export interface ReactNotificationOptions {
    // ...Other properties
    touchSlidingExit?: {
        fade: TransitionOptions;
        swipe: TransitionOptions;
    }
}
```

**Comment by aitorres** [comment]
A new version of `@types/react-notifications-component` v3.1 is available now with support for these values ☺️

**Comment by kennedykori** [comment]
Looks good, great job

**Comment by teodosii** [comment]
This is also present in the package and any typescript import  should see it properly

![image](https://user-images.githubusercontent.com/40542072/150680208-d501a8e4-7688-4fb7-aacc-a8f789f96234.png)

`3.1.0` release
