### ISSUE TITLE
Cannot install it on React 17.0.1

### ISSUE THREAD

**Issue by mjza** [teodosii/react-notifications-component#94]
```
npm install react-notifications-component
```

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: cimplycitywebapp@0.1.0
> npm ERR! Found: react@17.0.1
> npm ERR! node_modules/react
> npm ERR!   react@"^17.0.1" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.0.0" from react-notifications-component@3.0.3
> npm ERR! node_modules/react-notifications-component
> npm ERR!   react-notifications-component@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by kostaskonkk** [comment]
I am also having the same issue!

**Comment by oladipo** [comment]
any updates ? I have the same issue

**Comment by teodosii** [comment]
Try `3.0.4`, does it work?
Planning to release a `3.1.0` to have the other issues fixed but I'm low on time at the moment. Feel free to contribute any of you in case you want :)

**Comment by teodosii** [comment]
`3.0.4` has `react` updated to `17.0.1`

**Comment by PantsuNaniiro** [comment]
> Try `3.0.4`, does it work?
> Planning to release a `3.1.0` to have the other issues fixed but I'm low on time at the moment. Feel free to contribute any of you in case you want :)

I'm having the same problem with the version 3.0.4

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: david@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-notifications-component@3.0.4
npm ERR! node_modules/react-notifications-component
npm ERR!   react-notifications-component@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by raeudigerRaeffi** [comment]
I am facing the same issue, so far I tried to install the package with --force. However the libary is currently not useable in that state, because if I run the example as shown in the documents 
store.addNotification({
            title: "Wonderful!",
            message: "teodosii@react-notifications-component",
            type: "success",
            insert: "top",
            container: "top-right",
            animationIn: ["animate__animated", "animate__fadeIn"],
            animationOut: ["animate__animated", "animate__fadeOut"],
            dismiss: {
                duration: 5000,
                onScreen: true
            }
        });

I will get the following error message:
 ×
TypeError: this.add is not a function
Store.addNotification

  46 |      this.types,
  47 |      this.defaultNotificationWidth
  48 |    );
> 49 |    return this.add(parsedNotification);
     | ^  50 |  }
  51 | 
  52 |  public getCounter = () => this.counter;

**Comment by aitorres** [comment]
+1

Trying to install versions `3.0.3` and `3.0.4` both fail with the same error as before while using react `17.0.1`.

**Comment by teodosii** [comment]
Tested with CRA on build `3.0.5`, all working now!
Thanks for reporting the issue!

If the problem still persists feel free to reopen the issue.

**Comment by aitorres** [comment]
Hello! I'm still having the issue 😞

i have React 17 and tried to install this package, version 3.0.5, this is what I got:

```bash
$ aitorres@echo npm i --save react-notifications-component@3.0.5
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: project@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-notifications-component@3.0.5
npm ERR! node_modules/react-notifications-component
npm ERR!   react-notifications-component@"3.0.5" from the root project
```

Don't know if it's an error on my end or something related to the package's peer dependencies.

**Comment by teodosii** [comment]
Ohhhh, damn, you're right... didn't see it! Wonder why CRA didn't complain... Looking at the cra's package json it points to `v17`

![image](https://user-images.githubusercontent.com/40542072/112613439-c4693f80-8e28-11eb-9565-d49f8f87d1f8.png)

Deployed now `3.1.0` with peerDependencies updated to the same version.

**Comment by teodosii** [comment]
@aitorres let me know if there's any issue left. Hopefully there's none xD

**Comment by aitorres** [comment]
@teodosii All fine now! I could successfully install it on my app, thank you for helping with this! :D
