### ISSUE TITLE
How to close using javascript?

### ISSUE THREAD

**Issue by hopewise** [teodosii/react-notifications-component#96]
Is there a way to keep the notification open, and close it from code? (without user interaction and without a timer)
How would I do so? like if I have a reference for it, I do `my_notification.close();`

Kindly advice.

**Comment by varungupta85** [comment]
You can use the `removeNotification` method.

**Comment by hopewise** [comment]
Thanks, but how can I make it visible for ever until I remove it by self? is it just setting dismiss duration to very big number? or there is a better way?

**Comment by teodosii** [comment]
Use duration `0` for infinite.
